{
 "title": "AlienVault OSSIM - By Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "label": "Sensor Name",
    "query": "SELECT name AS __text, HEX(id) AS __value FROM sensor ORDER BY name;"
   }
  ]
 },
 "panels": [
  {
   "title": "List of Sensors",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  s.name AS sensor_name,\r\n  INET6_NTOA(s.ip) AS sensor_ip,\r\n  s.port,\r\n\r\n  sp.version AS agent_version,\r\n  sp.has_ntop,\r\n  sp.has_vuln_scanner,\r\n  sp.has_ossec,\r\n  sp.ids,\r\n  sp.passive_inventory,\r\n  sp.netflows,\r\n\r\n  sys.profile,\r\n  sys.ha_name,\r\n  sys.ha_role,\r\n  \r\n  s.priority,\r\n  s.tzone\r\nFROM\r\n  sensor s\r\nLEFT JOIN host h ON s.id = h.id\r\nLEFT JOIN host_ip hip ON h.id = hip.host_id\r\nLEFT JOIN sensor_properties sp ON s.id = sp.sensor_id\r\nLEFT JOIN system sys ON s.id = sys.sensor_id \r\nWHERE HEX(s.id) IN ($sensor_id)\r\nGROUP BY s.id;"
    }
   ]
  },
  {
   "title": "Top 10 most frequent attacks",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  ps.name AS Vulnerability,\r\n  COUNT(*) AS Events\r\nFROM event e\r\nJOIN plugin_sid ps ON e.plugin_id = ps.plugin_id AND e.plugin_sid = ps.sid\r\nWHERE $__timeFilter(e.timestamp) AND HEX(e.sensor_id) IN ($sensor_id)\r\nGROUP BY ps.name\r\nORDER BY Events DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Most Attacked Ports",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  CONCAT(dst_port, '/',\r\n    CASE protocol\r\n      WHEN 1 THEN 'ICMP'\r\n      WHEN 6 THEN 'TCP'\r\n      WHEN 17 THEN 'UDP'\r\n      ELSE CONCAT('Other(', protocol, ')')\r\n    END\r\n  ) AS 'Port/Protocol',\r\n  COUNT(*) AS Events\r\nFROM event\r\nWHERE dst_port IS NOT NULL\r\n  AND protocol IS NOT NULL\r\n  AND $__timeFilter(timestamp)\r\n  AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY dst_port, protocol\r\nORDER BY Events DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Events per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:00:00')) as time_sec,\r\n  COUNT(*) AS 'Events per hour' \r\nFROM event\r\nWHERE $__timeFilter(timestamp) AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY time_sec\r\nORDER BY time_sec ASC"
    }
   ]
  },
  {
   "title": "Events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(timestamp) as time_sec,\r\n  COUNT(*) as 'Events per minute' \r\nFROM event\r\nWHERE $__timeFilter(timestamp) AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY time_sec\r\nORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Top 10 Source IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  INET6_NTOA(src_ip) AS 'Source IP',\r\n  src_hostname AS 'Hostname',\r\n  COUNT(*) AS Events\r\nFROM event\r\nWHERE $__timeFilter(timestamp) AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY src_ip\r\nORDER BY Events DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 destination IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 46 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  INET6_NTOA(dst_ip) AS 'Destination IP',\r\n  dst_hostname AS 'Hostname',\r\n  COUNT(*) AS Events\r\nFROM event\r\nWHERE $__timeFilter(timestamp) AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY dst_ip\r\nORDER BY Events DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Source IP → Destination IP",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 14, "y": 46 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  CONCAT(\r\n    INET6_NTOA(src_ip), ' → ', INET6_NTOA(dst_ip),\r\n    ' : ',\r\n    dst_port,\r\n    '/',\r\n    CASE protocol\r\n      WHEN 1 THEN 'ICMP'\r\n      WHEN 6 THEN 'TCP'\r\n      WHEN 17 THEN 'UDP'\r\n      ELSE CONCAT('Other(', protocol, ')')\r\n    END\r\n  ) AS Flow,\r\n  COUNT(*) AS Events\r\nFROM event\r\nWHERE $__timeFilter(timestamp) AND HEX(sensor_id) IN ($sensor_id)\r\nGROUP BY Flow\r\nORDER BY Events DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Access to the OSSIM Administration Website",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "alienvault",
     "rawSql": "SELECT\r\n  date AS Date,\r\n  info AS Event,\r\n  login AS Username,\r\n  ipfrom AS 'Source IP'\r\nFROM\r\n  log_action\r\nWHERE $__timeFilter(date)\r\nORDER BY\r\n  date DESC"
    }
   ]
  }
 ]
}